import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const headerHeight = 50;
export const bottomBarHeight = 55;

const styles = StyleSheet.create({
  gradient: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerSpaceAround: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 16,
  },

  containerCenter: {
    width: '100%',
    height: '100%',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    gap: 8,
  },
  cardsListContainer: {
    flex: 1,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
  },
  card: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    padding: 8,
    backgroundColor: colors.transpWhite70,
  },
  scrollViewContainer: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 8,
    paddingVertical: 16,
  },
  scrollView: {
    height: '100%',
    width: '100%',
  },
  sectionAlignLeft: {
    width: '100%',
    gap: 8,
    paddingHorizontal: 16,
  },
  sectionAlignCenter: {
    width: '100%',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    textAlign: 'center',
  },
  cardsSection: {
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
  },
  inputContainer: {
    width: '80%',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 10,
    backgroundColor: colors.transpWhite70,
    padding: 16,
    gap: 16,
  },
  primaryInput: {
    width: '100%',
    borderBottomColor: colors.black,
    borderBottomWidth: 0.5,
    fontSize: 14,
    color: colors.black,
  },
  secondaryInput: {
    width: '100%',
    borderBottomColor: colors.white,
    borderBottomWidth: 0.5,
    fontSize: 14,
    color: colors.white,
  },
  appTitle: {
    color: colors.white,
    fontSize: 32,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  primaryTitle: {
    color: colors.white,
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  primarySubtitle: {
    color: colors.white,
    fontSize: 18,
    fontWeight: 'normal',
    textAlign: 'center',
  },
  primaryBodyText: {
    color: colors.white,
    width: '100%',
    fontSize: 14,
    fontWeight: 'normal',
  },
  primaryBodyTextBold: {
    color: colors.white,
    width: '100%',
    fontSize: 14,
    fontWeight: 'bold',
  },
  primaryMediumBodyText: {
    color: colors.white,
    width: '100%',
    fontSize: 12,
    fontWeight: 'normal',
  },
  primaryMediumBodyTextBold: {
    color: colors.white,
    width: '100%',
    fontSize: 12,
    fontWeight: 'bold',
  },
  primaryLightBodyText: {
    color: colors.white,
    width: '100%',
    fontSize: 10,
    fontWeight: 'normal',
  },
  primaryLightBodyTextBold: {
    color: colors.white,
    width: '100%',
    fontSize: 10,
    fontWeight: 'bold',
  },
  secondaryTitle: {
    color: colors.black,
    fontSize: 20,
    fontWeight: 'normal',
    textAlign: 'center',
  },
  secondarySubtitle: {
    color: colors.black,
    fontSize: 18,
    fontWeight: 'normal',
    textAlign: 'center',
  },
  secondaryBodyText: {
    color: colors.black,
    width: '100%',
    fontSize: 14,
    fontWeight: 'normal',
  },
  secondaryBodyTextBold: {
    color: colors.black,
    width: '100%',
    fontSize: 14,
    fontWeight: 'bold',
  },
  secondaryMediumBodyText: {
    color: colors.black,
    width: '100%',
    fontSize: 12,
    fontWeight: 'normal',
  },
  secondaryMediumBodyTextBold: {
    color: colors.black,
    width: '100%',
    fontSize: 12,
    fontWeight: 'bold',
  },
  secondaryLightBodyText: {
    color: colors.black,
    width: '100%',
    fontSize: 10,
    fontWeight: 'normal',
  },
  secondaryLightBodyTextBold: {
    color: colors.black,
    width: '100%',
    fontSize: 10,
    fontWeight: 'bold',
  },
  errorText: {
    color: colors.canceled,
    width: '100%',
    fontSize: 12,
    fontWeight: 'bold',
  },
  picture: {
    width: '100%',
    height: 250,
    resizeMode: 'cover',
    borderRadius: 10,
  },
  userPictureBadge: {
    height: 120,
    width: 120,
    backgroundColor: colors.white,
    borderRadius: 60,
    borderColor: colors.black,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
    resizeMode: 'cover',
  },
  userPictureMiniBadge: {
    height: 60,
    width: 60,
    backgroundColor: colors.white,
    borderRadius: 30,
    borderColor: colors.black,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    resizeMode: 'cover',
  },
  userNivelBadge: {
    height: 80,
    width: 80,
    backgroundColor: colors.white,
    borderRadius: 40,
    borderColor: colors.tertiary,
    borderWidth: 3,
    justifyContent: 'center',
    alignItems: 'center',
  },
  primaryButton: {
    width: 200,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    backgroundColor: colors.black,
    borderRadius: 10,
    color: colors.white,
    elevation: 4,
  },
  primaryButtonText: {
    color: colors.white,
    fontSize: 16,
    fontWeight: 'normal',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  secondaryButton: {
    width: 200,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    backgroundColor: 'transparent',
    borderRadius: 10,
    borderColor: colors.black,
    borderWidth: 1,
  },
  secondaryButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: 'normal',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  tertiaryButton: {
    width: 200,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    backgroundColor: colors.tertiary,
    borderRadius: 50,
    elevation: 4,
  },
  tertiaryButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: 'normal',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  textButton: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    marginTop: 32,
    backgroundColor: 'transparent',
  },
  textButtonText: {
    color: colors.black,
    fontSize: 16,
    fontWeight: 'normal',
    textAlign: 'center',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  iconButton: {
    width: 50,
    height: 50,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.black,
    borderRadius: 25,
  },
});

export default styles;
